[hosts.cadmium]
hostname = "cadmium.home.gio.ninja"
description = "My Desktop PC"
location = "home"

[hosts.californium]
hostname = "californium.home.gio.ninja"
description = "Critical Services"
location = "digitalocean.sfo3"
# Current list of services
#  - DNS Server for Tailscale network

[hosts.germanium]
hostname = "germanium.home.gio.ninja"
description = "Lenovo Chromebook"
location = "mobile"
