package main

import (
	"fmt"
	"os"
	"strings"

	"github.com/BurntSushi/toml"
)

// Config is the on-disk TOML config, generated by the NixOS module from the
// enabled deployedApps slots and the gio.deploy globals.
type Config struct {
	Gradient GradientConfig        `toml:"gradient"`
	Restate  RestateConfig         `toml:"restate"`
	Slots    map[string]SlotConfig `toml:"slots"`
}

type GradientConfig struct {
	// Server is the base URL of the Gradient instance (no trailing slash needed).
	Server string `toml:"server"`
	// APIKeyFile points at a read-scope Gradient API key (a systemd credential).
	APIKeyFile string `toml:"api_key_file"`
}

type RestateConfig struct {
	// ServiceName is the Restate Virtual Object name this binary registers as.
	// It encodes the host (e.g. "gradient-deployer-carbon") so each host is a
	// distinct Restate deployment.
	ServiceName string `toml:"service_name"`
}

type SlotConfig struct {
	// Project is the "<org>/<project>" slug used for the Gradient API.
	Project string `toml:"project"`
	// Profile is the nix profile symlink to point at the deployed build.
	Profile string `toml:"profile"`
	// RestartUnit is the systemd unit to restart after the profile changes.
	RestartUnit string `toml:"restart_unit"`
}

// LoadConfig parses and validates the TOML config at path.
func LoadConfig(path string) (*Config, error) {
	var cfg Config
	if _, err := toml.DecodeFile(path, &cfg); err != nil {
		return nil, fmt.Errorf("parsing config: %w", err)
	}

	if cfg.Gradient.Server == "" {
		return nil, fmt.Errorf("gradient.server is required")
	}
	if cfg.Gradient.APIKeyFile == "" {
		return nil, fmt.Errorf("gradient.api_key_file is required")
	}
	if cfg.Restate.ServiceName == "" {
		return nil, fmt.Errorf("restate.service_name is required")
	}
	for name, slot := range cfg.Slots {
		if slot.Project == "" {
			return nil, fmt.Errorf("slot %q: project is required", name)
		}
		if slot.Profile == "" {
			return nil, fmt.Errorf("slot %q: profile is required", name)
		}
		if slot.RestartUnit == "" {
			return nil, fmt.Errorf("slot %q: restart_unit is required", name)
		}
	}

	return &cfg, nil
}

// ResolveAPIKey reads and trims the Gradient API key from its file.
func ResolveAPIKey(cfg *Config) (string, error) {
	data, err := os.ReadFile(cfg.Gradient.APIKeyFile)
	if err != nil {
		return "", fmt.Errorf("reading api key (%s): %w", cfg.Gradient.APIKeyFile, err)
	}
	return strings.TrimSpace(string(data)), nil
}
