name: Flake Build
on:
  push:
    branches:
      - "main"
jobs:
  flake-health-checker:
    name: Check Flake Health
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v4
