name: Build Portable Neovim
on:
  push:
    branches:
      - "main"
    paths:
      - "flake.lock"
      - "nix/packages/neovim/**"
      - ".github/workflows/portable-neovim.yml"
jobs:
  build-appimage:
    name: Build AppImage
    runs-on: ubuntu-latest
    env:
      BUCKET_NAME: gio-neovim-appimages
      FILE_NAME: nvim.${{ github.sha }}.AppImage
    steps:
      - name: Free Up Disk Space for Nix
        uses: wimpysworld/nothing-but-nix@main
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: cachix/cachix-action@v14
        with:
          name: nixos-configs
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build AppImage
        run: nix bundle --bundler github:ralismark/nix-appimage .#neovim
      - name: Upload to Backblaze
        id: backblaze-upload
        env:
          B2_APPLICATION_KEY: ${{ secrets.B2_APPLICATION_KEY }}
          B2_APPLICATION_KEY_ID: ${{ secrets.B2_APPLICATION_KEY_ID }}
        run: |
          nix run nixpkgs#backblaze-b2 -- file upload $BUCKET_NAME nvim.AppImage $FILE_NAME
          # Always keep a copy of the latest build without it's ref+sha
          nix run nixpkgs#backblaze-b2 -- file server-side-copy b2://$BUCKET_NAME/$FILE_NAME b2://$BUCKET_NAME/nvim.AppImage
          # Save Download URL
          DOWNLOAD_URL=$(nix run nixpkgs#backblaze-b2 -- file url b2://$BUCKET_NAME/$FILE_NAME)
          echo "DOWNLOAD_URL=$DOWNLOAD_URL" >> $GITHUB_OUTPUT
      - name: Generate Run Instructions
        run: |
          echo "# Run Custom Neovim Image" >> $GITHUB_STEP_SUMMARY
          echo "    \$ curl -LO ${{ steps.backblaze-upload.outputs.DOWNLOAD_URL }}" >> $GITHUB_STEP_SUMMARY
          echo "    \$ chmod +x $FILE_NAME" >> $GITHUB_STEP_SUMMARY
          echo "    \$ ./$FILE_NAME" >> $GITHUB_STEP_SUMMARY
